import = [
    "~/.config/alacritty/theme-colors.toml",
    "~/.config/alacritty/os-specific.toml",
]

[scrolling]
history = 0

[window]
startup_mode = "Maximized"

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { style = "Bold" }
size = 18.0
offset = { x = 0, y = 2 }

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true