[colors.primary]
background = '#eaeaea'
foreground = '#000000'

[colors.normal]
black = '#000000'
red = '#ff0000'
green = '#009900'
yellow = '#d19a66'
blue = '#0000ff'
magenta = '#990099'
cyan = '#77ccbb'
white = '#eaeaea'

[colors.bright]
black = '#000000'
red = '#ff0000'
green = '#009900'
yellow = '#d19a66'
blue = '#0000ff'
magenta = '#aa00aa'
cyan = '#77ccbb'
white = '#666666'

[colors.cursor]
cursor = "#000000"
text = "#ffffff"
